package com.example.stock.presentation.ui.theme

import androidx.compose.ui.graphics.Color


val light_primary = Color(0xFF2E5DA8)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFE4EEFF)
val light_onPrimaryContainer = Color(0xFF001A40)
val light_secondary = Color(0xFF86AFF3)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFDBE1FF)
val light_onSecondaryContainer = Color(0xFF00174B)
val light_tertiary = Color(0xFF805600)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFF0E4)
val light_onTertiaryContainer = Color(0xFF281800)
val light_error = Color(0xFFd6504f)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFEFBFF)
val light_onBackground = Color(0xFF1B1B1F)
val light_surface = Color(0xFFFEFBFF)
val light_onSurface = Color(0xFF1B1B1F)
val light_surfaceVariant = Color(0xFFE0E2EC)
val light_onSurfaceVariant = Color(0xFF44474E)
val light_outline = Color(0xFF74777F)
val light_inverseOnSurface = Color(0xFFF2F0F4)
val light_inverseSurface = Color(0xFF2F3033)
val light_inversePrimary = Color(0xFFACC7FF)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF2E5DA8)
val light_outlineVariant = Color(0xFFC4C6D0)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFACC7FF)
val dark_onPrimary = Color(0xFF002F67)
val dark_primaryContainer = Color(0xFF08458E)
val dark_onPrimaryContainer = Color(0xFFD7E2FF)
val dark_secondary = Color(0xFFB4C5FF)
val dark_onSecondary = Color(0xFF002A77)
val dark_secondaryContainer = Color(0xFF003EA7)
val dark_onSecondaryContainer = Color(0xFFDBE1FF)
val dark_tertiary = Color(0xFFFDBA4B)
val dark_onTertiary = Color(0xFF442C00)
val dark_tertiaryContainer = Color(0xFF614000)
val dark_onTertiaryContainer = Color(0xFFFFDDAF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1B1B1F)
val dark_onBackground = Color(0xFFE3E2E6)
val dark_surface = Color(0xFF1B1B1F)
val dark_onSurface = Color(0xFFE3E2E6)
val dark_surfaceVariant = Color(0xFF44474E)
val dark_onSurfaceVariant = Color(0xFFC4C6D0)
val dark_outline = Color(0xFF8E9099)
val dark_inverseOnSurface = Color(0xFF1B1B1F)
val dark_inverseSurface = Color(0xFFE3E2E6)
val dark_inversePrimary = Color(0xFF2E5DA8)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFACC7FF)
val dark_outlineVariant = Color(0xFF44474E)
val dark_scrim = Color(0xFF000000)

//custom colors
val green = Color(0xFF4CAF50)